'use client';

import React,{useEffect,useMemo,useState} from 'react';
import AppLayout from '@/components/AppLayout';
import AuthGuard from '@/components/AuthGuard';
import {createClient} from '@/lib/supabase/client';
import {useAuth} from '@/contexts/AuthContext';
import {toast} from 'sonner';

type Profile={id:string;full_name:string|null;email:string|null;employee_code:string|null;branch:string|null};
type Call={id:string;created_at:string;assigned_user_id:string|null;contact_name:string|null;contact_phone:string|null;outcome:string|null;call_status:string|null;call_duration:number|null;notes:string|null;lead_id:string|null;ai_score:number|null;ai_summary:string|null;ai_coaching:string|null;ai_next_action:string|null;ai_analyzed_at:string|null};
type App={id:string;sales_user_id:string;appointment_at:string;appointment_type:string;status:string;lead_id:string|null};
type Lead={id:string;name:string;phone:string;source_category:string|null;status:string;user_id:string|null;last_outcome:string|null;next_follow_up_at:string|null;joined_at:string|null;next_action:string|null};
const SOURCES=['expired','old','social_media','invitation','tour','follow_up'];
const label=(s:string)=>({expired:'Expired',old:'Old',social_media:'Social Media',invitation:'Invitation',tour:'Tour',follow_up:'Follow-up'}[s]||s);
const badOutcome=(o:string|null)=>['no_answer','busy','failed','wrong_number','canceled'].includes(o||'');
const joinedOutcome=(o:string|null)=>['joined','converted'].includes(o||'');

export default function SalesControlRoom(){
 const {user}=useAuth();
 const [profiles,setProfiles]=useState<Profile[]>([]),[calls,setCalls]=useState<Call[]>([]),[apps,setApps]=useState<App[]>([]),[leads,setLeads]=useState<Lead[]>([]);
 const [tab,setTab]=useState<'live'|'team'|'action'|'pipeline'|'sources'|'quality'|'intelligence'|'ai'>('live');
 const [date,setDate]=useState(()=>new Date().toISOString().slice(0,10)),[employee,setEmployee]=useState('all'),[source,setSource]=useState('all'),[loading,setLoading]=useState(true);

 const load=async()=>{
  if(!user)return;setLoading(true);const s=createClient();const start=new Date(date+'T00:00:00').toISOString(),end=new Date(date+'T23:59:59.999').toISOString();
  const [{data:p,error:pe},{data:c,error:ce},{data:a,error:ae},{data:l,error:le}]=await Promise.all([
   s.from('user_profiles').select('id,full_name,email,employee_code,branch').in('role',['sales_staff','branch_manager']).eq('is_active',true),
   s.from('call_logs').select('id,created_at,assigned_user_id,contact_name,contact_phone,outcome,call_status,call_duration,notes,lead_id').gte('created_at',start).lte('created_at',end).order('created_at',{ascending:false}).range(0,9999),
   s.from('sales_appointments').select('id,sales_user_id,appointment_at,appointment_type,status,lead_id').gte('appointment_at',start).lte('appointment_at',end).order('appointment_at',{ascending:true}).range(0,9999),
   s.from('leads').select('id,name,phone,source_category,status,user_id,last_outcome,next_follow_up_at,joined_at,next_action').order('created_at',{ascending:false}).range(0,9999)
  ]);
  const err=pe||ce||ae||le;if(err){toast.error(err.message);setLoading(false);return;}
  setProfiles((p||[]) as Profile[]);setCalls((c||[]) as Call[]);setApps((a||[]) as App[]);setLeads((l||[]) as Lead[]);setLoading(false);
 };
 useEffect(()=>{load();const t=setInterval(load,30000);return()=>clearInterval(t)},[user?.id,date]);

 const name=(id:string|null)=>{const p=profiles.find(x=>x.id===id);return p?.full_name||p?.email||'غير محدد'};
 const leadMap=useMemo(()=>new Map(leads.map(l=>[l.id,l])),[leads]);
 const sourceOf=(c:Call)=>c.lead_id?(leadMap.get(c.lead_id)?.source_category||'old'):'old';
 const filteredCalls=useMemo(()=>calls.filter(c=>(employee==='all'||c.assigned_user_id===employee)&&(source==='all'||sourceOf(c)===source)),[calls,employee,source,leadMap]);
 const rows=useMemo(()=>profiles.map(p=>{const cs=calls.filter(c=>c.assigned_user_id===p.id),as=apps.filter(a=>a.sales_user_id===p.id);const connected=cs.filter(c=>!badOutcome(c.outcome)).length,talk=cs.reduce((n,c)=>n+(c.call_duration||0),0);return {p,cs,connected,talk,appointments:as.filter(a=>a.appointment_type==='appointment').length,tours:as.filter(a=>a.appointment_type==='tour').length,joined:cs.filter(c=>joinedOutcome(c.outcome)).length,active:cs.filter(c=>['initiated','ringing','in-progress'].includes(c.call_status||'')).length};}),[profiles,calls,apps]);
 const totals=useMemo(()=>({calls:filteredCalls.length,connected:filteredCalls.filter(c=>!badOutcome(c.outcome)).length,talk:filteredCalls.reduce((n,c)=>n+(c.call_duration||0),0),joined:filteredCalls.filter(c=>joinedOutcome(c.outcome)).length,active:filteredCalls.filter(c=>['initiated','ringing','in-progress'].includes(c.call_status||'')).length,quality:filteredCalls.filter(c=>!c.outcome||!c.notes||(c.call_duration||0)<20).length}),[filteredCalls]);
 const overdue=useMemo(()=>leads.filter(l=>l.next_follow_up_at&&new Date(l.next_follow_up_at)<new Date()&&l.status!=='converted'&&l.status!=='lost').filter(l=>employee==='all'||l.user_id===employee).sort((a,b)=>new Date(a.next_follow_up_at!).getTime()-new Date(b.next_follow_up_at!).getTime()),[leads,employee]);
 const appointments=useMemo(()=>apps.filter(a=>employee==='all'||a.sales_user_id===employee),[apps,employee]);
 const intelligence=useMemo(()=>{const alerts:{level:'high'|'medium'|'info';title:string;detail:string}[]=[];if(totals.calls<pace)alerts.push({level:'high',title:'Call Pace Alert',detail:`الفريق أقل من الـpace المطلوب بـ ${pace-totals.calls} مكالمة.`});if(overdue.length)alerts.push({level:'high',title:'Follow-up Backlog',detail:`يوجد ${overdue.length} متابعة متأخرة تحتاج تنفيذ.`});const noAnswer=filteredCalls.filter(c=>['no_answer','busy'].includes(c.outcome||'')).length;if(noAnswer&&pct(noAnswer,filteredCalls.length)>=50)alerts.push({level:'medium',title:'Low Contact Rate',detail:`نسبة عدم الوصول مرتفعة: ${pct(noAnswer,filteredCalls.length)}%. راجع جودة البيانات وتوقيت الاتصال.`});if(totals.quality)alerts.push({level:'medium',title:'Quality Review',detail:`${totals.quality} مكالمة تحتاج مراجعة قبل إغلاق اليوم.`});return {alerts,employeeActions:rows.filter(r=>employee==='all'||r.p.id===employee).map(r=>({name:name(r.p.id),calls:r.cs.length,gap:Math.max(0,pace-r.cs.length),joined:r.joined,quality:r.cs.filter(c=>!c.outcome||!c.notes||(c.call_duration||0)<20).length}))};},[totals,pace,overdue,filteredCalls,rows,employee]);
 const nextAction=(l:Lead)=>l.status==='new'?'اتصال أولي + تحديد احتياج':l.next_follow_up_at&&new Date(l.next_follow_up_at)<new Date()?'متابعة متأخرة — اتصل الآن':l.status==='interested'?'حجز Appointment / Tour':l.status==='contacted'?'Follow-up + اعتراض السعر/التوقيت':l.next_action||'مراجعة الحالة';
 const pct=(n:number,d:number)=>d?Math.round(n/d*100):0;
 const pace=useMemo(()=>{if(date!==new Date().toISOString().slice(0,10))return 90;const h=new Date().getHours()+new Date().getMinutes()/60;return Math.min(90,Math.max(0,Math.round(((Math.max(0,Math.min(16,h)-8))/8)*90)));},[date]);
 const exportSheet=async()=>{try{const XLSX=await import('xlsx');const wb=XLSX.utils.book_new();
  const team=rows.map(r=>({Employee:name(r.p.id),Code:r.p.employee_code||'',Branch:r.p.branch||'',Calls:r.cs.length,Target:90,TargetPct:pct(r.cs.length,90),PaceTarget:pace,Connected:r.connected,AnswerRate:pct(r.connected,r.cs.length),TalkMinutes:Math.round(r.talk/60),Appointments:r.appointments,Tours:r.tours,Joined:r.joined,Conversion:pct(r.joined,r.cs.length),ActiveCalls:r.active}));
  const logs=filteredCalls.map(c=>({Time:new Date(c.created_at).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}),Employee:name(c.assigned_user_id),Lead:c.contact_name||'',Phone:c.contact_phone||'',Source:label(sourceOf(c)),Status:c.call_status||'',Outcome:c.outcome||'',Duration:c.call_duration||0,Notes:c.notes||''}));
  const follow=overdue.map(l=>({Lead:l.name,Phone:l.phone,Employee:name(l.user_id),Source:label(l.source_category||'old'),NextFollowUp:l.next_follow_up_at?new Date(l.next_follow_up_at).toLocaleString('en-GB'):'',LastOutcome:l.last_outcome||'',NextAction:l.next_action||''}));
  const sources=SOURCES.map(s=>{const cs=filteredCalls.filter(c=>sourceOf(c)===s);return {Source:label(s),Calls:cs.length,Connected:cs.filter(c=>!badOutcome(c.outcome)).length,Joined:cs.filter(c=>joinedOutcome(c.outcome)).length};});
  [['Team Sheet',team],['Call Log',logs],['Overdue Follow-ups',follow],['Source Sheet',sources]].forEach(([n,data])=>XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(data as any[]),String(n)));XLSX.writeFile(wb,'Energy-Plus-Sales-Control-'+date+'.xlsx');toast.success('تم تصدير شيت الإدارة');
 }catch(e){toast.error('تعذر تصدير الشيت');}};
 return <AuthGuard><AppLayout currentPath="/sales-control-room"><div dir="rtl" className="space-y-5">
  <div className="flex flex-col xl:flex-row xl:items-center justify-between gap-3"><div><h1 className="text-2xl font-800">Sales Control Room</h1><p className="text-sm text-muted-foreground mt-1">غرفة تحكم كاملة للمكالمات، المتابعات، الـPipeline وجودة تنفيذ الفريق · تحديث تلقائي 30 ثانية</p></div><div className="flex flex-wrap gap-2"><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="px-3 py-2 rounded-lg border border-border bg-background"/><button onClick={load} className="px-4 py-2 rounded-lg border border-border">تحديث الآن</button><button onClick={exportSheet} className="px-4 py-2 rounded-lg bg-primary text-primary-foreground font-700">Export Excel</button></div></div>
  <div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-6 gap-3">{[['Calls',totals.calls],['Pace Target',pace],['Connected',totals.connected],['Talk Time',Math.floor(totals.talk/60)+'m'],['Joined',totals.joined],['Active / QC',totals.active+' / '+totals.quality]].map(([k,v])=><div key={String(k)} className="bg-card border border-border rounded-xl p-4"><div className="text-2xl font-800">{v}</div><div className="text-xs text-muted-foreground mt-1">{k}</div></div>)}</div>
  <div className="grid md:grid-cols-3 gap-3"><div className="bg-card border border-border rounded-xl p-4"><div className="text-xs text-muted-foreground">المطلوب حتى الآن</div><div className="text-2xl font-800 mt-1">{pace} / 90</div><div className="text-xs mt-2">{totals.calls>=pace?'الفريق داخل الـpace':'الفريق متأخر '+(pace-totals.calls)+' مكالمة عن الـpace'}</div></div><div className="bg-card border border-border rounded-xl p-4"><div className="text-xs text-muted-foreground">Overdue Follow-ups</div><div className="text-2xl font-800 mt-1">{overdue.length}</div><div className="text-xs mt-2">Leads تحتاج تدخل الآن</div></div><div className="bg-card border border-border rounded-xl p-4"><div className="text-xs text-muted-foreground">Appointments / Tours</div><div className="text-2xl font-800 mt-1">{appointments.length}</div><div className="text-xs mt-2">مواعيد اليوم للفريق</div></div></div>
  <div className="flex flex-wrap gap-2 bg-muted/40 p-2 rounded-xl">{([['live','Live Monitor'],['team','Team Sheet'],['action','Action Center'],['pipeline','Pipeline'],['sources','Source Sheet'],['quality','Quality Control'],['intelligence','Manager Intelligence'],['ai','AI Call Coach']] as const).map(([k,v])=><button key={k} onClick={()=>setTab(k)} className={`px-4 py-2 rounded-lg text-sm ${tab===k?'bg-card shadow font-700':''}`}>{v}</button>)}</div>
  <div className="flex flex-wrap gap-2"><select value={employee} onChange={e=>setEmployee(e.target.value)} className="px-3 py-2 rounded-lg border border-border bg-background"><option value="all">كل الموظفين</option>{profiles.map(p=><option key={p.id} value={p.id}>{name(p.id)}</option>)}</select><select value={source} onChange={e=>setSource(e.target.value)} className="px-3 py-2 rounded-lg border border-border bg-background"><option value="all">كل المصادر</option>{SOURCES.map(s=><option key={s} value={s}>{label(s)}</option>)}</select></div>
  {tab==='live'&&<div className="bg-card border border-border rounded-xl overflow-hidden"><div className="p-4 border-b border-border flex justify-between"><b>Live Monitor</b><span className="text-xs text-muted-foreground">آخر 50 مكالمة</span></div>{loading?<div className="p-10 text-center">جاري التحميل...</div>:filteredCalls.slice(0,50).map(c=><div key={c.id} className="p-4 border-b border-border/60 flex flex-col md:flex-row md:items-center gap-3"><div className="flex-1"><div className="font-700">{c.contact_name||'Unknown'} <span className="text-xs text-muted-foreground">· {name(c.assigned_user_id)}</span></div><div className="text-xs text-muted-foreground mt-1">{new Date(c.created_at).toLocaleTimeString('ar-EG')} · {c.contact_phone||''} · {label(sourceOf(c))}</div></div><span className="px-2 py-1 rounded-lg bg-muted text-xs">{c.call_status||'—'}</span><span className="px-2 py-1 rounded-lg bg-primary/10 text-xs">{c.outcome||'بدون نتيجة'}</span><span className="text-sm tabular-nums">{c.call_duration||0}s</span></div>)}{!loading&&!filteredCalls.length&&<div className="p-10 text-center text-muted-foreground">لا توجد مكالمات في هذا اليوم.</div>}</div>}
  {tab==='team'&&<div className="bg-card border border-border rounded-xl overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-muted/30 border-b border-border"><th className="p-3 text-right">الموظف</th><th>Calls / 90</th><th>Pace</th><th>Connected</th><th>Answer %</th><th>Talk</th><th>Appt.</th><th>Tours</th><th>Joined</th><th>Conv.</th><th>Active</th></tr></thead><tbody>{rows.filter(r=>employee==='all'||r.p.id===employee).map(r=><tr key={r.p.id} className="border-b border-border/60"><td className="p-3 text-right font-600">{name(r.p.id)}</td><td className="text-center">{r.cs.length}/90</td><td className="text-center">{r.cs.length>=pace?'On pace':'Behind'}</td><td className="text-center">{r.connected}</td><td className="text-center">{pct(r.connected,r.cs.length)}%</td><td className="text-center">{Math.floor(r.talk/60)}m</td><td className="text-center">{r.appointments}</td><td className="text-center">{r.tours}</td><td className="text-center">{r.joined}</td><td className="text-center">{pct(r.joined,r.cs.length)}%</td><td className="text-center">{r.active}</td></tr>)}</tbody></table></div>}
  {tab==='action'&&<div className="grid lg:grid-cols-2 gap-4"><div className="bg-card border border-border rounded-xl overflow-hidden"><div className="p-4 border-b border-border"><b>🚨 Overdue Follow-ups</b></div>{overdue.slice(0,30).map(l=><div key={l.id} className="p-4 border-b border-border/60 flex items-center gap-3"><div className="flex-1"><b>{l.name}</b><div className="text-xs text-muted-foreground">{l.phone} · {name(l.user_id)} · {label(l.source_category||'old')}</div><div className="text-xs mt-1">كان مطلوب متابعة: {new Date(l.next_follow_up_at!).toLocaleString('ar-EG')}</div></div><a href={`tel:${l.phone}`} className="px-3 py-2 rounded-lg bg-positive text-white text-sm">اتصال</a></div>)}{!overdue.length&&<div className="p-8 text-center text-muted-foreground">لا توجد متابعات متأخرة.</div>}</div><div className="bg-card border border-border rounded-xl overflow-hidden"><div className="p-4 border-b border-border"><b>📅 Today's Appointments</b></div>{appointments.slice(0,30).map(a=><div key={a.id} className="p-4 border-b border-border/60"><b>{a.appointment_type}</b><span className="text-sm"> · {new Date(a.appointment_at).toLocaleTimeString('ar-EG',{hour:'2-digit',minute:'2-digit'})}</span><div className="text-xs text-muted-foreground mt-1">{name(a.sales_user_id)} · {a.status} · {leadMap.get(a.lead_id||'')?.name||'Lead'}</div></div>)}{!appointments.length&&<div className="p-8 text-center text-muted-foreground">لا توجد مواعيد اليوم.</div>}</div></div>}
  {tab==='pipeline'&&<div className="grid md:grid-cols-2 xl:grid-cols-5 gap-3">{[['new','New'],['contacted','Contacted'],['interested','Interested'],['converted','Joined'],['lost','Lost']].map(([st,title])=>{const ls=leads.filter(l=>l.status===st&&(employee==='all'||l.user_id===employee)&&(source==='all'||(l.source_category||'old')===source));return <div key={st} className="bg-card border border-border rounded-xl overflow-hidden"><div className="p-3 border-b border-border font-700">{title} <span className="text-xs text-muted-foreground">({ls.length})</span></div><div className="max-h-[520px] overflow-y-auto">{ls.slice(0,50).map(l=><div key={l.id} className="p-3 border-b border-border/50"><b className="text-sm">{l.name}</b><div className="text-xs text-muted-foreground">{l.phone}</div><div className="text-[11px] mt-1">{name(l.user_id)} · {label(l.source_category||'old')}</div>{l.next_follow_up_at&&<div className="text-[11px] mt-1">Next: {new Date(l.next_follow_up_at).toLocaleString('ar-EG')}</div>}</div>)}</div></div>})}</div>}
  {tab==='sources'&&<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{SOURCES.map(s=>{const cs=filteredCalls.filter(c=>sourceOf(c)===s),con=cs.filter(c=>!badOutcome(c.outcome)).length,j=cs.filter(c=>joinedOutcome(c.outcome)).length;return <div key={s} className="bg-card border border-border rounded-xl p-5"><div className="font-700">{label(s)}</div><div className="grid grid-cols-3 gap-2 mt-4 text-center"><div><b>{cs.length}</b><p className="text-xs text-muted-foreground">Calls</p></div><div><b>{con}</b><p className="text-xs text-muted-foreground">Connected</p></div><div><b>{j}</b><p className="text-xs text-muted-foreground">Joined</p></div></div><div className="text-xs text-muted-foreground mt-3">Connect rate: {pct(con,cs.length)}% · Join rate: {pct(j,cs.length)}%</div></div>})}</div>}
  {tab==='intelligence'&&<div className="space-y-4"><div className="grid lg:grid-cols-2 gap-4"><div className="bg-card border border-border rounded-xl overflow-hidden"><div className="p-4 border-b border-border"><b>🧠 Manager Intelligence</b><p className="text-xs text-muted-foreground mt-1">تنبيهات تشغيلية تلقائية مبنية على بيانات اليوم.</p></div>{intelligence.alerts.map((a,i)=><div key={i} className="p-4 border-b border-border/60"><b>{a.level==='high'?'🚨':a.level==='medium'?'⚠️':'ℹ️'} {a.title}</b><div className="text-sm mt-1 text-muted-foreground">{a.detail}</div></div>)}{!intelligence.alerts.length&&<div className="p-8 text-center text-positive">لا توجد تنبيهات تشغيلية حالياً.</div>}</div><div className="bg-card border border-border rounded-xl overflow-hidden"><div className="p-4 border-b border-border"><b>🎯 Employee Action Plan</b><p className="text-xs text-muted-foreground mt-1">الـgap المطلوب لكل موظف + جودة التنفيذ.</p></div>{intelligence.employeeActions.map((r,i)=><div key={i} className="p-4 border-b border-border/60"><div className="flex justify-between"><b>{r.name}</b><span className="text-xs">{r.calls} calls</span></div><div className="grid grid-cols-3 gap-2 mt-3 text-center text-sm"><div><b>{r.gap}</b><p className="text-[11px] text-muted-foreground">Calls Gap</p></div><div><b>{r.joined}</b><p className="text-[11px] text-muted-foreground">Joined</p></div><div><b>{r.quality}</b><p className="text-[11px] text-muted-foreground">QC</p></div></div></div>)}</div></div><div className="bg-card border border-border rounded-xl overflow-hidden"><div className="p-4 border-b border-border"><b>⚡ Next Best Action Queue</b><p className="text-xs text-muted-foreground mt-1">أولوية التنفيذ لكل Lead.</p></div>{leads.filter(l=>l.status!=='converted'&&l.status!=='lost').filter(l=>employee==='all'||l.user_id===employee).sort((a,b)=>{const ax=a.next_follow_up_at?new Date(a.next_follow_up_at).getTime():Infinity,bx=b.next_follow_up_at?new Date(b.next_follow_up_at).getTime():Infinity;return ax-bx}).slice(0,40).map(l=><div key={l.id} className="p-4 border-b border-border/60 flex items-center gap-3"><div className="flex-1"><b>{l.name}</b><div className="text-xs text-muted-foreground">{name(l.user_id)} · {label(l.source_category||'old')} · {l.phone}</div></div><span className="px-2 py-1 rounded-lg bg-muted text-xs">{nextAction(l)}</span><a href={`tel:${l.phone}`} className="px-3 py-2 rounded-lg bg-primary text-primary-foreground text-xs">اتصال</a></div>)}</div></div>}
  {tab==='ai'&&<div className="space-y-4"><div className="bg-card border border-border rounded-xl p-5"><b>🤖 AI Call Coach</b><p className="text-sm text-muted-foreground mt-1">تحليل تلقائي لكل مكالمة مسجلة في الـCRM بناءً على مدة المكالمة، النتيجة والملاحظات. عند إضافة تسجيل صوتي لاحقاً يمكن ربطه بتحليل صوتي حقيقي.</p><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-4"><div className="bg-muted/40 rounded-xl p-4"><div className="text-2xl font-800">{Math.round(filteredCalls.filter(c=>c.ai_score!==null).reduce((n,c)=>n+(c.ai_score||0),0)/(filteredCalls.filter(c=>c.ai_score!==null).length||1))}</div><div className="text-xs text-muted-foreground">Average AI Score</div></div><div className="bg-muted/40 rounded-xl p-4"><div className="text-2xl font-800">{filteredCalls.filter(c=>(c.ai_score||0)>=80).length}</div><div className="text-xs text-muted-foreground">Strong Calls</div></div><div className="bg-muted/40 rounded-xl p-4"><div className="text-2xl font-800">{filteredCalls.filter(c=>(c.ai_score||0)<60&&c.ai_score!==null).length}</div><div className="text-xs text-muted-foreground">Needs Coaching</div></div><div className="bg-muted/40 rounded-xl p-4"><div className="text-2xl font-800">{filteredCalls.filter(c=>c.ai_score!==null).length}</div><div className="text-xs text-muted-foreground">Analyzed</div></div></div></div><div className="bg-card border border-border rounded-xl overflow-hidden"><div className="p-4 border-b border-border"><b>Call-by-Call Coaching</b></div>{filteredCalls.filter(c=>c.ai_score!==null).slice(0,50).map(c=><div key={c.id} className="p-4 border-b border-border/60"><div className="flex flex-wrap items-center gap-2"><b>{c.contact_name||'Unknown'}</b><span className="text-xs text-muted-foreground">· {name(c.assigned_user_id)}</span><span className="px-2 py-1 rounded-lg bg-primary/10 text-xs">AI {c.ai_score}/100</span><span className="text-xs">{c.outcome||'No outcome'}</span></div><div className="text-sm mt-2">{c.ai_coaching||'Review call structure and next action.'}</div><div className="text-xs text-muted-foreground mt-1">Next: {c.ai_next_action||'Set a dated follow-up.'}</div></div>)}{!filteredCalls.some(c=>c.ai_score!==null)&&<div className="p-10 text-center text-muted-foreground">لسه مفيش مكالمات محللة. أول مكالمة جديدة بعد التحديث هتظهر هنا.</div>}</div></div>}
  {tab==='quality'&&<div className="bg-card border border-border rounded-xl overflow-hidden"><div className="p-4 border-b border-border"><b>Quality Control</b><p className="text-xs text-muted-foreground mt-1">المكالمات التي تحتاج مراجعة: بدون نتيجة، بدون ملاحظات، أو أقل من 20 ثانية.</p></div>{filteredCalls.filter(c=>!c.outcome||!c.notes||(c.call_duration||0)<20).slice(0,100).map(c=><div key={c.id} className="p-4 border-b border-border/60 flex flex-col md:flex-row gap-2 md:items-center"><div className="flex-1"><b>{c.contact_name||'Unknown'}</b><span className="text-xs text-muted-foreground"> · {name(c.assigned_user_id)}</span></div><span className="text-xs">مدة: {c.call_duration||0}s</span><span className="text-xs">{c.outcome?'Outcome ✓':'Outcome ناقص'}</span><span className="text-xs">{c.notes?'Notes ✓':'Notes ناقصة'}</span></div>)}{!filteredCalls.some(c=>!c.outcome||!c.notes||(c.call_duration||0)<20)&&<div className="p-10 text-center text-positive">لا توجد مكالمات تحتاج مراجعة.</div>}</div>}
 </div></AppLayout></AuthGuard>
}